const APPLICATION_SERVER = process.env.REACT_APP_APPLICATION_SERVER
const APPLICATION_VERSION = process.env.REACT_APP_APPLICATION_VERSION
const APPLICATION_SOCKETS = process.env.REACT_APP_APPLICATION_SOCKETS
const PAYMENT_SECRET_KEY = process.env.REACT_APP_PAYMENT_SECRET_KEY
const MERCHANT_ACCOUNT = process.env.REACT_APP_MERCHANT_ACCOUNT
const MERCHANT_DOMAIN_NAME = process.env.REACT_APP_MERCHANT_DOMAIN_NAME
const MERCHANT_ID = process.env.REACT_APP_MERCHANT_ID
const DIALOGS_COUNT_OF_UPLOADING_MESSAGES = 50
const CHANNEL_COUNT_OF_UPLOADING_MESSAGES = 50
const DIALOGS_COUNT_OF_UPLOADING_CHATS = 15
const LEVELS_COUNT_OF_UPLOADING = 20
const CONTACTS_COUNT_OF_UPLOADING = 15
const ADMIN_PAYMENTS_COUNT_OF_UPLOADING = 20
const CHANNEL_LIST_COUNT_OF_UPLOADING_ITEMS = 15
const NOTIFICATIONS_COUNT_OF_UPLOADING = 15

export {
  APPLICATION_SERVER,
  APPLICATION_VERSION,
  APPLICATION_SOCKETS,
  PAYMENT_SECRET_KEY,
  MERCHANT_ACCOUNT,
  MERCHANT_DOMAIN_NAME,
  DIALOGS_COUNT_OF_UPLOADING_MESSAGES,
  CHANNEL_COUNT_OF_UPLOADING_MESSAGES,
  DIALOGS_COUNT_OF_UPLOADING_CHATS,
  LEVELS_COUNT_OF_UPLOADING,
  CONTACTS_COUNT_OF_UPLOADING,
  ADMIN_PAYMENTS_COUNT_OF_UPLOADING,
  MERCHANT_ID,
  CHANNEL_LIST_COUNT_OF_UPLOADING_ITEMS,
  NOTIFICATIONS_COUNT_OF_UPLOADING,
}
